# Generated by Django 5.2.9 on 2025-12-14 09:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('backup_email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('jti', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('is_blacklisted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='api.user')),
            ],
            options={
                'db_table': 'refresh_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('login_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=2, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('isp', models.CharField(blank=True, max_length=200, null=True)),
                ('user_agent', models.TextField()),
                ('device_type', models.CharField(blank=True, max_length=20, null=True)),
                ('device_fingerprint', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('browser', models.CharField(blank=True, max_length=50, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=20, null=True)),
                ('os', models.CharField(blank=True, max_length=50, null=True)),
                ('os_version', models.CharField(blank=True, max_length=20, null=True)),
                ('login_method', models.CharField(max_length=20)),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('failure_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('refresh_token', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_event', to='api.refreshtoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_events', to='api.user')),
            ],
            options={
                'db_table': 'login_events',
                'ordering': ['-login_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('RESTORE_PASSWORD', 'restore_password'), ('VERIFY_EMAIL', 'verify_email'), ('BACKUP_EMAIL', 'backup_email')], max_length=16)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to='api.user')),
            ],
            options={
                'db_table': 'verification_codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'code'], name='verificatio_user_id_07c2d7_idx')],
            },
        ),
    ]
