# Generated by Django 5.2.9 on 2025-12-28 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginevent',
            options={'ordering': ['-login_at'], 'verbose_name': 'Событие входа', 'verbose_name_plural': 'События входа'},
        ),
        migrations.AlterModelOptions(
            name='refreshtoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'Токен обновления', 'verbose_name_plural': 'Токены обновления'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='verificationcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Проверочный код', 'verbose_name_plural': 'Проверочные коды'},
        ),
        migrations.RemoveIndex(
            model_name='verificationcode',
            name='verificatio_user_id_07c2d7_idx',
        ),
        migrations.AlterModelTable(
            name='loginevent',
            table=None,
        ),
        migrations.AlterModelTable(
            name='refreshtoken',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
        migrations.AlterModelTable(
            name='verificationcode',
            table=None,
        ),
    ]
