# Generated by Django 5.2.9 on 2025-12-29 16:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_loginevent_options_alter_refreshtoken_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refreshtoken',
            options={'ordering': ['chain__id', '-created_at'], 'verbose_name': 'Токен обновления', 'verbose_name_plural': 'Токены обновления'},
        ),
        migrations.RenameField(
            model_name='refreshtoken',
            old_name='is_blacklisted',
            new_name='is_revoked',
        ),
        migrations.RemoveField(
            model_name='loginevent',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='refreshtoken',
            name='user',
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('remember_me', models.BooleanField(default=False)),
                ('login_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chain', to='api.loginevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chains', to='api.user')),
            ],
            options={
                'verbose_name': 'Цепочка токенов',
                'verbose_name_plural': 'Цепочки токенов',
                'ordering': ['user__id'],
            },
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='chain',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='api.chain'),
            preserve_default=False,
        ),
    ]
