# Generated by Django 5.2.9 on 2026-01-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_refreshtoken_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='purpose',
            field=models.CharField(choices=[('RESTORE_PASSWORD', 'restore_password'), ('VERIFY_EMAIL', 'verify_email'), ('VERIFY_BACKUP_EMAIL', 'verify_backup_email')], max_length=19),
        ),
    ]
