# Generated by Django 5.2.9 on 2025-12-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('secret_hash', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('dev_host', models.CharField(max_length=255)),
                ('prod_host', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
            },
        ),
    ]
