# Generated by Django 5.2.9 on 2026-01-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_service_dev_host_remove_service_prod_host'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
